name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    uses: eqworks/common-workflows/.github/workflows/js-main.yml@main
    secrets:
      CD_GITHUB_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
  chromatic:
    uses: eqworks/common-workflows/.github/workflows/js-chromatic.yml@main
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      CD_GITHUB_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
