export default {
  'dev-table-1': {
    'title': 'table example widget',
    'type': 'table',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'submitted_deals',
        'title': 'Submitted deals',
      },
      {
        'key': 'approved_deals',
        'title': 'Approved deals',
      },
      {
        'key': 'funded_deals',
        'title': 'Funded deals',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'resolution',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Resolution',
    'uniqueOptions': {
      'showTicks': true,
      'spline': false,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': true,
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1830',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-stat-1': {
    'title': 'stat example widget',
    'type': 'stat',
    'filters': [
      {
        key: 'resolution',
        filter: [20000],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'submitted_deals',
        'title': 'Submitted deals',
      },
      {
        'key': 'approved_deals',
        'title': 'Approved deals',
      },
      {
        'key': 'funded_deals',
        'title': 'Funded deals',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'resolution',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Resolution',
    'uniqueOptions': {
      'showTicks': true,
      'spline': false,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': true,
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1830',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-pie-1': {
    'title': 'My example pie widget',
    'type': 'pie',
    'filters': [
      {
        'key': 'city_clicks',
        'filter': [
          20,
          308,
        ],
      },
    ],
    'groupFilter': [
      'LAVAL',
      'MONTREAL',
      'MIRABEL',
      'BROSSARD',
    ],
    'valueKeys': [
      {
        'key': 'city_clicks',
        'title': 'City clicks (mean)',
        'agg': 'mean',
      },
      {
        'key': 'city_impressions',
        'title': 'City impressions (sum)',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'geo_ca_city',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Geo ca city',
    'uniqueOptions': {
      'showPercentage': true,
      'donut': true,
    },
    'genericOptions': {
      'groupByValue': false,
      'showLegend': true,
      'subPlots': true,
      'size': 0.6,
      'titlePosition': [
        0.5,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'baseColor': '#f2ff00',
      'showWidgetTitle': false,
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '187',
    },
  },
  'dev-pie-2': {
    'title': 'Percentage widget',
    'type': 'pie',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'renters',
        'title': 'Renters (mean)',
        'agg': 'mean',
      },
      {
        'key': 'owners',
        'title': 'Owners (mean)',
        'agg': 'mean',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'city',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'City',
    'uniqueOptions': {
      'showPercentage': true,
      'donut': false,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': true,
      'showLegend': true,
      'subPlots': true,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Execution',
      'id': '141',
    },
  },
  'dev-pie-3': {
    'title': 'Paymi Sample 1',
    'type': 'pie',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'Dollars Rewarded',
        'title': 'Dollars Rewarded (mean)',
        'agg': 'mean',
      },
      {
        'key': 'Number of Transactions',
        'title': 'Number of Transactions (sum)',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'consumer_gender',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Consumer gender',
    'uniqueOptions': {
      'donut': false,
      'showPercentage': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': true,
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'mapViewState': {
      'latitude': 44.41,
      'longitude': -79.23,
      'zoom': 7,
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1591',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
  },
  'dev-bar-1': {
    'title': 'My example bar widget',
    'type': 'bar',
    'filters': [
      {
        'key': 'city_clicks',
        'filter': [
          30,
          138,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'converted_users',
        'title': 'Converted users (mean)',
        'agg': 'mean',
      },
      {
        'key': 'city_clicks',
        'title': 'City clicks (sum)',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'geo_ca_city',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Geo ca city',
    'uniqueOptions': {
      'stacked': true,
      'showTicks': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'subPlots': false,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        1,
      ],
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '187',
    },
  },
  'dev-bar-2': {
    'title': 'Time/Price Widget',
    'type': 'bar',
    'filters': [],
    'groupFilter': [
      '2019-08-28',
      '2020-08-27',
    ],
    'valueKeys': [
      {
        'key': 'price',
        'title': 'Price (mean)',
        'agg': 'mean',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'time',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Time',
    'uniqueOptions': {
      'stacked': false,
      'showTicks': true,
      'spline': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'subPlots': true,
      'size': 0.8,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1458',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
    'dateAggregation': 'Hour',
  },
  'dev-bar-3' : {
    'title': 'My example bar - benchmark widget',
    'type': 'bar',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'title': 'Visitation',
        'key': 'visitation',
      },
      {
        'key': 'city',
        'title': 'City',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'location_category',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Location category',
    'uniqueOptions': {
      'stacked': false,
      'showTicks': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': false,
      'showSubPlotTitles': true,
      'showLabels': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'subPlots': false,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        0.5,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#363ee3',
    },
    'dataSource': {
      'type': 'Manual',
      'id': '2000',
    },
    'percentageMode': false,
    'addUserControls': true,
    'userControlHeadline': 'Benchmark by',
    'userControlKeyValues': [
      'city',
      'provincial',
      'national',
    ],
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#363ee3',
    ],
    'mapTooltipLabelTitles': null,
  },
  'dev-line-1': {
    'title': 'Another Line Widget',
    'type': 'line',
    'filters': [
      {
        'key': 'clicks',
        'filter': [
          117,
          423,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'clicks',
        'title': 'Clicks',
      },
      {
        'key': 'revenue',
        'title': 'Revenue',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': false,
    'groupKey': null,
    'mapGroupKey': null,
    'indexKey': 'impressions',
    'indexKeyTitle': 'Impressions',
    'uniqueOptions': {
      'spline': true,
      'showTicks': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'subPlots': true,
      'size': 0.8,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '191',
    },
  },
  'dev-line-2': {
    'title': 'My example line widget',
    'type': 'line',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'spend',
        'title': 'Spend',
      },
      {
        'key': 'clicks',
        'title': 'Clicks',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': false,
    'groupKey': null,
    'mapGroupKey': null,
    'indexKey': 'impressions',
    'indexKeyTitle': 'Impressions',
    'uniqueOptions': {
      'spline': false,
      'showTicks': true,
    },
    'genericOptions': {
      'groupByValue': false,
      'showLegend': true,
      'subPlots': false,
      'size': 0.2,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        1,
      ],
      'baseColor': '#366fe4',
      'showWidgetTitle': true,
    },
    'dataSource': {
      'type': 'Execution',
      'id': '305',
    },
  },
  'dev-scatter-1': {
    'title': 'My example scatter widget',
    'type': 'scatter',
    'filters': [
      {
        'key': 'unique_visitors',
        'filter': [
          0,
          1474,
        ],
      },
      {
        'key': 'repeat_visitors',
        'filter': [
          43,
          399,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'unique_visitors',
        'title': 'Unique visitors',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': false,
    'groupKey': null,
    'mapGroupKey': null,
    'indexKey': 'repeat_visitors',
    'indexKeyTitle': 'Repeat visitors',
    'uniqueOptions': {
      'showTicks': true,
      'showLines': false,
    },
    'genericOptions': {
      'showWidgetTitle': true,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0.5,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '217',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-map-1': {
    'title': 'My example map widget - polygon geojson layer FSA & postal code',
    'type': 'map',
    'filters': [
      {
        'key': 'spend',
        'filter': [
          0,
          100,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [],
    'mapValueKeys': [
      {
        'mapVis': 'elevation',
        'key': 'impressions',
        'title': 'Impressions (sum)',
        'agg': 'sum',
      },
      {
        'title': 'Spend (sum)',
        'mapVis': 'fill',
        'key': 'spend',
        'agg': 'sum',
      },
    ],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': null,
    'mapGroupKey': 'geo_cohort_fsa',
    'indexKey': null,
    'mapGroupKeyTitle': 'Geo cohort fsa',
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'elevation': {
        'value': 10000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 30,
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': true,
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'mapViewState': {
      'value': {
        'latitude': 44.4,
        'longitude': -79.23,
        'zoom': 7,
      },
      'postalCode': {
        'latitude': 43.75,
        'longitude': -79.4,
        'zoom': 10,
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1389',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
  },
  'dev-map-2': {
    'title': 'My example map widget - scatterplot layer',
    'type': 'map',
    'filters': [
      {
        'key': 'visits',
        'filter': [
          0,
          100,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [],
    'mapValueKeys': [
      {
        'mapVis': 'radius',
        'key': 'visits',
        'title': 'Visits (sum)',
        'agg': 'sum',
      },
      {
        'title:': 'Unique visitors (sum)',
        'mapVis': 'fill',
        'key': 'unique_visitors',
        'agg': 'sum',
      },
    ],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': null,
    'mapGroupKey': 'poi_id',
    'indexKey': null,
    'mapGroupKeyTitle': 'Poi id',
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'elevation': {
        'value': 1000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 20,
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': true,
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'mapViewState': {
      'value': {
        'latitude': 49.04458924229672,
        'longitude': -87.95359000000006,
        'zoom': 2.9427361735841195,
        'width': 917,
        'height': 742,
        'bearing': 0,
        'pitch': 0,
        'altitude': 1.5,
        'maxZoom': 20,
        'minZoom': 0,
        'maxPitch': 60,
        'minPitch': 0,
      },
      'postalCode': {
        'latitude': 43.75,
        'longitude': -79.4,
        'zoom': 10,
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '913',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-map-3': {
    'title': 'My example map widget - xwi report',
    'type': 'map',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': null,
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'targetRadius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'targetFill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'arcWidth': {
        'value': 1,
        'valueOptions': [
          1,
          20,
        ],
      },
      'elevation': {
        'value': 1000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 20,
      },
      'size': {
        'value': 4,
      },
      'mapViewState': {
        'value': {
          'latitude': 49.95629223186103,
          'longitude': -95.2493957499999,
          'zoom': 3.5259095514967456,
          'width': 808,
          'height': 834,
          'bearing': 0,
          'pitch': 45,
          'altitude': 1.5,
          'maxZoom': 20,
          'minZoom': 0,
          'maxPitch': 60,
          'minPitch': 0,
          'position': [
            0,
            0,
            0,
          ],
        },
        'postalCode': {
          'latitude': 43.75,
          'longitude': -79.4,
          'zoom': 10,
        },
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': true,
      'showSubPlotTitles': true,
      'showLabels': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Execution',
      'id': '2123',
    },
    'percentageMode': false,
    'addUserControls': false,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [],
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
    'mapTooltipLabelTitles': {
      'sourceTitle': 'Poi name',
    },
  },
  'dev-map-4': {
    'title': 'My example map widget - user value controls',
    'type': 'map',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [],
    'mapValueKeys': [
      {
        'mapVis': 'fill',
        'key': 'no_education',
        'title': 'No education',
      },
    ],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': null,
    'mapGroupKey': 'geo_ca_fsa',
    'indexKey': null,
    'mapGroupKeyTitle': 'Geo ca fsa',
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'targetRadius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'targetFill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'arcWidth': {
        'value': 1,
        'valueOptions': [
          1,
          20,
        ],
      },
      'elevation': {
        'value': 10000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 30,
      },
      'size': {
        'value': 4,
      },
      'mapViewState': {
        'value': {
          'latitude': 43.69729166871382,
          'longitude': -79.30322360425139,
          'zoom': 11.250307063380061,
          'width': 1028,
          'height': 837,
          'bearing': 0,
          'pitch': 0,
          'altitude': 1.5,
          'maxZoom': 20,
          'minZoom': 0,
          'maxPitch': 60,
          'minPitch': 0,
          'position': [
            0,
            0,
            0,
          ],
        },
        'postalCode': {
          'latitude': 43.75,
          'longitude': -79.4,
          'zoom': 10,
        },
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': true,
      'showSubPlotTitles': true,
      'showLabels': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Manual',
      'id': '3000',
    },
    'percentageMode': false,
    'addUserControls': true,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [
      'population',
      'home_value',
      'no_education',
      'secondary_education',
      'apprenticeship_trades',
      'college_uni_below_bachelor',
      'uni_bachelor',
      'uni_advanced',
    ],
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
    'mapTooltipLabelTitles': null,
  },
  'filter-test-1': {
    'title': 'Household income',
    'type': 'bar',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'title': '0-50%',
        'key': 'hh_income_0_50',
      },
      {
        'title': '50-100%',
        'key': 'hh_income_50_100',
      },
      {
        'title': '100-150%',
        'key': 'hh_income_100_150',
      },
      {
        'title': '150-200%',
        'key': 'hh_income_150_200',
      },
      {
        'key': 'hh_income_200_over',
        'title': '200%+',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'resolution',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Resolution',
    'uniqueOptions': {
      'stacked': false,
      'showTicks': true,
      'donut': false,
      'showPercentage': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': true,
      'showLegend': false,
      'showTooltip': true,
      'showAxisTitles': false,
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': '#366fe4',
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1825',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
  },
  'dev-pyramid-1': {
    'title': 'My example pyramid widget',
    'type': 'pyramid',
    'filters': [
      {
        'key': 'city_clicks',
        'filter': [
          30,
          138,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'converted_users',
        'title': 'Converted users (mean)',
        'agg': 'mean',
      },
      {
        'key': 'city_clicks',
        'title': 'City clicks (sum)',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'geo_ca_city',
    'mapGroupKey': null,
    'indexKey': null,
    'groupKeyTitle': 'Geo ca city',
    'uniqueOptions': {
      'showPercentage': false,
      'showTicks': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'subPlots': false,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        1,
      ],
      'baseColor': '#366fe4',
      'xAxisLabelLength': 5,
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '187',
    },
  },
}
