export default {
  'dev-table-1': {
    'title': 'table example widget',
    'showTitleBar': true,
    'type': 'table',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': ' Dollars Spent ',
        'agg': 'sum',
      },
      {
        'key': 'Dollars Rewarded',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'category_name',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'hidePagination': true,
      'headerTitle': true,
      'compactTable': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1591',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-table-2': {
    'title': 'table2 example widget',
    'showTitleBar': true,
    'type': 'table',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': ' Dollars Spent ',
        'agg': 'sum',
      },
      {
        'key': 'Dollars Rewarded',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'category_name',
    'mapGroupKey': null,
    'indexKey': null,
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1591',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-stat-1': {
    'title': 'stat example widget',
    'showTitleBar': true,
    'type': 'stat',
    'filters': [],
    'groupFilter': ['5000'],
    'valueKeys': [
      {
        'key': 'submitted_deals',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'resolution',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'showTicks': true,
      'spline': false,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLabels': true,
      'showCurrency': false,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1830',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-stat-2': {
    'title': 'stat trend example',
    'showTitleBar': true,
    'type': 'stat',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'submitted_deals',
        'agg': 'sum',
      },
      {
        'key': 'funded_deals',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'dealerId',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'showTicks': true,
      'spline': false,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLabels': true,
      'showCurrency': false,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
    },
    'dataSource': {
      'type': 'Manual',
      'id': '2001',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-pie-1': {
    'title': 'My example pie widget',
    'showTitleBar': true,
    'type': 'pie',
    'filters': [
      {
        'key': 'city_clicks',
        'filter': [
          20,
          308,
        ],
      },
    ],
    'groupFilter': [
      'LAVAL',
      'MONTREAL',
      'MIRABEL',
      'BROSSARD',
    ],
    'valueKeys': [
      {
        'key': 'city_clicks',
        'agg': 'mean',
      },
      {
        'key': 'city_impressions',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'geo_ca_city',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'showPercentage': true,
      'donut': true,
    },
    'genericOptions': {
      'groupByValue': false,
      'showLegend': true,
      'subPlots': true,
      'size': 0.6,
      'titlePosition': [
        0.5,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'showWidgetTitle': false,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '187',
    },
  },
  'dev-pie-2': {
    'title': 'Percentage widget',
    'showTitleBar': true,
    'type': 'pie',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'renters',
        'agg': 'mean',
      },
      {
        'key': 'owners',
        'agg': 'mean',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'city',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'showPercentage': true,
      'donut': false,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': true,
      'showLegend': true,
      'subPlots': true,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '141',
    },
  },
  'dev-pie-3': {
    'title': 'Paymi Sample 1',
    'showTitleBar': true,
    'type': 'pie',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'Dollars Rewarded',
        'agg': 'mean',
      },
      {
        'key': 'Number of Transactions',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'consumer_gender',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'donut': false,
      'showPercentage': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1591',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
  },
  'dev-pie-4': {
    'title': 'My example pie widget with customColors',
    'subtitle': '',
    'subtitleLinkLabel': '',
    'subtitleHyperlink': '',
    'showTitleBar': true,
    'type': 'pie',
    'filters': [
      {
        'key': 'city_clicks',
        'filter': [
          20,
          308,
        ],
      },
    ],
    'groupFilter': [
      'LAVAL',
      'MONTREAL',
      'MIRABEL',
      'BROSSARD',
    ],
    'valueKeys': [
      {
        'key': 'city_clicks',
        'agg': 'mean',
      },
      {
        'key': 'city_impressions',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'columnNameAliases': {},
    'group': true,
    'groupKey': 'geo_ca_city',
    'mapGroupKey': null,
    'useMVTOption': true,
    'indexKey': null,
    'uniqueOptions': {
      'donut': false,
      'showPercentage': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'showCurrency': false,
      'showVertical': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'showLocationPins': false,
      'mapPinTooltipKey': '',
      'subPlots': true,
      'size': 0.6,
      'titlePosition': [
        0.5,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'labelPosition': 'Bottom',
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '187',
    },
    'percentageMode': false,
    'addUserControls': false,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [],
    'addTopCategories': false,
    'categoryFilter': null,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#f2ff00',
    ],
    'mapTooltipLabelTitles': null,
    'customColors': {
      'chart': [
        '#004C86',
        '#CF7047',
        '#1F7F79',
        '#B24456',
        '#582A7D',
        '#D3A642',
        '#3175AC',
        '#7A002D',
        '#437345',
        '#802C6D',
      ],
      'map': {
        'targetLayerColor': '',
        'iconColor': '#CF7047',
      },
    },
  },
  'dev-bar-1': {
    'title': 'My example bar widget',
    'showTitleBar': true,
    'type': 'bar',
    'filters': [
      {
        'key': 'city_clicks',
        'filter': [
          30,
          138,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'converted_users',
        'agg': 'mean',
      },
      {
        'key': 'city_clicks',

        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'columnNameAliases': {
      'geo_ca_city': 'City',
      'city_clicks': 'Clicks',
    },
    'group': true,
    'groupKey': 'geo_ca_city',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'stacked': true,
      'showTicks': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'subPlots': false,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        1,
      ],
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'showAxisTitles': {
        'x': true,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '187',
    },
  },
  'dev-bar-2': {
    'title': 'Time/Price Widget',
    'showTitleBar': true,
    'type': 'bar',
    'filters': [],
    'groupFilter': [
      '2019-08-28',
      '2020-08-27',
    ],
    'valueKeys': [
      {
        'key': 'price',
        'agg': 'mean',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'time',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'stacked': false,
      'showTicks': true,
      'spline': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'subPlots': true,
      'size': 0.8,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'showAxisTitles': {
        'x': true,
        'y': true,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1458',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
    'dateAggregation': 'Hour',
  },
  'dev-bar-3' : {
    'title': 'My example bar - benchmark widget',
    'showTitleBar': true,
    'type': 'bar',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'visitation',
      },
      {
        'key': 'city',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'location_category',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'stacked': false,
      'showTicks': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'subPlots': false,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        0.5,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
    },
    'dataSource': {
      'type': 'Manual',
      'id': '2000',
    },
    'percentageMode': false,
    'addUserControls': true,
    'userControlHeadline': 'Top 10 Consumer Spending Categories    Benchmark by',
    'userControlKeyValues': [
      'city',
      'provincial',
      'national',
    ],
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#363ee3',
    ],
    'mapTooltipLabelTitles': null,
  },
  'dev-bar-4' : {
    'title': 'Insights on Top 10 Consumer Spending Categories',
    'subtitle': 'Check sub-categories of the Top 10 Spending Categories in your Market Area.',
    'subtitleLinkLabel': 'Learn More',
    'subtitleHyperlink': 'https://www.eqworks.com/',
    'showTitleBar': true,
    'type': 'bar',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'market_area',
      },
      {
        'key': 'city',
      },
      {
        'key': 'province',
      },
      {
        'key': 'country',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'name',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'stacked': false,
      'showTicks': true,
      'horizontal': false,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': true,
      },
      'axisTitles': {
        'x': '',
        'y': 'Score',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'showCurrency': false,
      'showVertical': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        0.5,
        0,
      ],
      'labelPosition': 'Bottom',
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
    },
    'dataSource': {
      'type': 'Manual',
      'id': '4000',
    },
    'percentageMode': false,
    'addUserControls': false,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [],
    'addTopCategories': true,
    'categoryFilter': null,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#00548a',
    ],
    'mapTooltipLabelTitles': null,
    'wl': 2423,
  },
  'dev-line-1': {
    'title': 'Another Line Widget',
    'showTitleBar': true,
    'type': 'line',
    'filters': [
      {
        'key': 'clicks',
        'filter': [
          117,
          423,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'clicks',
      },
      {
        'key': 'revenue',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': false,
    'groupKey': null,
    'mapGroupKey': null,
    'indexKey': 'impressions',
    'uniqueOptions': {
      'spline': true,
      'showTicks': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'subPlots': true,
      'size': 0.8,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'showAxisTitles': {
        'x': true,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '191',
    },
  },
  'dev-line-2': {
    'title': 'My example line widget',
    'showTitleBar': true,
    'type': 'line',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'spend',
      },
      {
        'key': 'clicks',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': false,
    'groupKey': null,
    'mapGroupKey': null,
    'indexKey': 'impressions',
    'uniqueOptions': {
      'spline': false,
      'showTicks': true,
    },
    'genericOptions': {
      'groupByValue': false,
      'showLegend': true,
      'subPlots': false,
      'size': 0.2,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        1,
      ],
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'showWidgetTitle': true,
      'showAxisTitles': {
        'x': true,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '305',
    },
  },
  'dev-barline-1' : {
    'title': 'My example barline',
    'subtitle': '',
    'subtitleLinkLabel': '',
    'subtitleHyperlink': '',
    'showTitleBar': true,
    'type': 'barLine',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'visitation',
      },
    ],
    'chart2ValueKeys': [
      {
        'key': 'city',
        'type': 'line',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'columnNameAliases': {},
    'formattedColumnNames': {
      'location_category': 'Location category',
      'visitation': 'Visitation',
      'city': 'City',
      'provincial': 'Provincial',
      'national': 'National',
    },
    'group': true,
    'groupKey': 'location_category',
    'mapGroupKey': null,
    'useMVTOption': true,
    'indexKey': null,
    'uniqueOptions': {
      'showTicks': true,
      'showLineMarkers': true,
      'sharedYAxis': true,
      'lineFill': false,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': true,
        'y': true,
        'y2': true,
      },
      'axisTitles': {
        'x': '',
        'y': '',
        'y2': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'showCurrency': false,
      'showVertical': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'showLocationPins': false,
      'mapPinTooltipKey': '',
      'subPlots': false,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        0.5,
        0,
      ],
      'labelPosition': 'Bottom',
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
      'chart1ZPosition': 'Back',
    },
    'dataSource': {
      'type': 'Manual',
      'id': '2000',
    },
    'percentageMode': false,
    'addUserControls': false,
    'userControlHeadline': '',
    'userControlKeyValues': [],
    'addTopCategories': false,
    'categoryFilter': null,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#363ee3',
    ],
    'mapTooltipLabelTitles': null,
  },
  'dev-scatter-1': {
    'title': 'My example scatter widget',
    'showTitleBar': true,
    'type': 'scatter',
    'filters': [
      {
        'key': 'unique_visitors',
        'filter': [
          0,
          1474,
        ],
      },
      {
        'key': 'repeat_visitors',
        'filter': [
          43,
          399,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'unique_visitors',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': false,
    'groupKey': null,
    'mapGroupKey': null,
    'indexKey': 'repeat_visitors',
    'uniqueOptions': {
      'showTicks': true,
      'showLines': false,
    },
    'genericOptions': {
      'showWidgetTitle': true,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0.5,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'showAxisTitles': {
        'x': true,
        'y': true,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '217',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-map-1': {
    'title': 'My example map widget - polygon geojson layer FSA & postal code',
    'subtitle': '',
    'subtitleLinkLabel': '',
    'subtitleHyperlink': '',
    'showTitleBar': true,
    'type': 'map',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [],
    'chart2ValueKeys': [],
    'mapValueKeys': [
      {
        'mapVis': 'fill',
        'key': 'Pickup',
      },
    ],
    'formatDataFunctions': {},
    'columnNameAliases': {},
    'formattedColumnNames': {
      'dealer_id': 'Dealer id',
      'geo_ca_postalcode': 'Geo ca postalcode',
      'Dealer': 'Dealer',
      'geometry': 'Geometry',
      'type': 'Type',
      'Sedan': 'Sedan',
      'Coupe': 'Coupe',
      'Pickup': 'Pickup',
      'SUV': 'SUV',
      'Wagon': 'Wagon',
      'Luxury': 'Luxury',
    },
    'group': true,
    'groupKey': null,
    'mapGroupKey': 'geo_ca_postalcode',
    'useMVTOption': false,
    'indexKey': null,
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'targetRadius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'targetFill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'arcWidth': {
        'value': 1,
        'valueOptions': [
          1,
          20,
        ],
      },
      'elevation': {
        'value': 10000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 30,
      },
      'size': {
        'value': 4,
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
        'y2': true,
      },
      'axisTitles': {
        'x': '',
        'y': '',
        'y2': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'showCurrency': false,
      'showVertical': false,
      'addAggregationLabel': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'showLocationPins': false,
      'mapPinTooltipKey': '',
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'labelPosition': 'Bottom',
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
      'chart1ZPosition': 'Back',
    },
    'noDataSource': false,
    'dataSource': {
      'type': 'Manual',
      'id': '6000',
    },
    'percentageMode': false,
    'addUserControls': false,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [],
    'addTopCategories': false,
    'categoryFilter': null,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
    'mapTooltipLabelTitles': null,
    'customColors': {},
  },
  'dev-map-2': {
    'title': 'My example map widget - scatterplot layer',
    'subtitle': '',
    'subtitleLinkLabel': '',
    'subtitleHyperlink': '',
    'showTitleBar': true,
    'type': 'map',
    'filters': [
      {
        'key': 'visits',
        'filter': [
          0,
          100,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [],
    'mapValueKeys': [
      {
        'mapVis': 'radius',
        'key': 'visits',
        'agg': 'sum',
      },
      {
        'mapVis': 'fill',
        'key': 'unique_visitors',
        'agg': 'sum',
      },
    ],
    'formatDataFunctions': {},
    'columnNameAliases': {
      'address_city': 'City',
    },
    'group': true,
    'groupKey': null,
    'mapGroupKey': 'poi_id',
    'indexKey': null,
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'targetRadius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'targetFill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'arcWidth': {
        'value': 1,
        'valueOptions': [
          1,
          20,
        ],
      },
      'elevation': {
        'value': 1000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 20,
      },
      'size': {
        'value': 4,
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'showCurrency': false,
      'showVertical': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'showLocationPins': true,
      'mapPinTooltipKey': 'address_city',
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'labelPosition': 'Bottom',
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
    },
    'dataSource': {
      'type': 'Execution',
      'id': '913',
    },
    'percentageMode': false,
    'addUserControls': false,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [],
    'addTopCategories': false,
    'categoryFilter': null,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
    'mapTooltipLabelTitles': null,
  },
  'dev-map-3': {
    'title': 'My example map widget - xwi report',
    'showTitleBar': true,
    'type': 'map',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': null,
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'targetRadius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'targetFill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'arcWidth': {
        'value': 1,
        'valueOptions': [
          1,
          20,
        ],
      },
      'elevation': {
        'value': 1000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 20,
      },
      'size': {
        'value': 4,
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '2123',
    },
    'percentageMode': false,
    'addUserControls': false,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [],
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
  },
  'dev-map-4': {
    'title': 'My example map widget - user value controls',
    'subtitle': '',
    'subtitleLinkLabel': '',
    'subtitleHyperlink': '',
    'showTitleBar': false,
    'type': 'map',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [],
    'mapValueKeys': [
      {
        'mapVis': 'fill',
        'key': 'Total Population',
      },
    ],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': null,
    'mapGroupKey': 'geo_ca_fsa',
    'useMVTOption': true,
    'indexKey': null,
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'targetRadius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'targetFill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'arcWidth': {
        'value': 1,
        'valueOptions': [
          1,
          20,
        ],
      },
      'elevation': {
        'value': 10000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 30,
      },
      'size': {
        'value': 4,
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'showCurrency': false,
      'showVertical': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'labelPosition': 'Bottom',
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
    },
    'dataSource': {
      'type': 'Manual',
      'id': '3000',
    },
    'percentageMode': false,
    'addUserControls': true,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [
      'Total Population',
      'home_value',
      'highest_education_no_education',
      'highest_education_secondary_education',
      'highest_education_apprenticeship_trades',
      'highest_education_college_uni_below_bachelor',
      'highest_education_uni_bachelor',
      'highest_education_uni_advanced',
    ],
    'addTopCategories': false,
    'categoryFilter': null,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
    'mapTooltipLabelTitles': null,
  },
  'dev-map-5':{
    'title': 'My example map widget - user value controls - top segments',
    'subtitle': '',
    'showTitleBar': true,
    'type': 'map',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [],
    'mapValueKeys': [
      {
        'mapVis': 'fill',
        'key': 'health_and_beauty',
        'agg': 'unique',
      },
    ],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': null,
    'mapGroupKey': 'geo_ca_fsa',
    'useMVTOption': true,
    'indexKey': null,
    'uniqueOptions': {
      'radius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'fill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'targetRadius': {
        'value': 10,
        'valueOptions': [
          5,
          15,
        ],
      },
      'targetFill': {
        'value': [
          39,
          85,
          196,
        ],
        'valueOptions': [
          [
            214,
            232,
            253,
          ],
          [
            39,
            85,
            196,
          ],
        ],
      },
      'arcWidth': {
        'value': 1,
        'valueOptions': [
          1,
          20,
        ],
      },
      'elevation': {
        'value': 10000,
      },
      'lineWidth': {
        'value': 1,
      },
      'opacity': {
        'value': 30,
      },
      'size': {
        'value': 4,
      },
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': false,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'showCurrency': false,
      'showVertical': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'labelPosition': 'Bottom',
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
    },
    'dataSource': {
      'type': 'Manual',
      'id': '5000',
    },
    'percentageMode': false,
    'addUserControls': true,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [
      'arts_aficionados',
      'health_and_beauty',
      'small_business_owners',
      'readers',
      'car_owner',
      'students',
      'small_business_insights',
      'online_savvy_shoppers',
    ],
    'addTopCategories': false,
    'categoryFilter': 'segment_type',
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
    'mapTooltipLabelTitles': null,
  },
  'filter-test-1': {
    'title': 'Household income',
    'showTitleBar': true,
    'type': 'bar',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'hh_income_0_50',
      },
      {
        'key': 'hh_income_50_100',
      },
      {
        'key': 'hh_income_100_150',
      },
      {
        'key': 'hh_income_150_200',
      },
      {
        'key': 'hh_income_200_over',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'resolution',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'stacked': false,
      'showTicks': true,
      'donut': false,
      'showPercentage': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': true,
      'showLegend': false,
      'showTooltip': true,
      'showAxisTitles': {
        'x': true,
        'y': false,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
      'showSubPlotTitles': true,
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
    },
    'dataSource': {
      'type': 'Execution',
      'id': '1825',
    },
    'percentageMode': false,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
  },
  'dev-pyramid-1': {
    'title': 'My example pyramid widget',
    'showTitleBar': true,
    'type': 'pyramid',
    'filters': [
      {
        'key': 'city_clicks',
        'filter': [
          30,
          138,
        ],
      },
    ],
    'groupFilter': [],
    'valueKeys': [
      {
        'key': 'converted_users',
        'agg': 'mean',
      },
      {
        'key': 'city_clicks',
        'agg': 'sum',
      },
    ],
    'mapValueKeys': [],
    'formatDataFunctions': {},
    'group': true,
    'groupKey': 'geo_ca_city',
    'mapGroupKey': null,
    'indexKey': null,
    'uniqueOptions': {
      'showPercentage': false,
      'showTicks': true,
    },
    'genericOptions': {
      'showWidgetTitle': false,
      'groupByValue': false,
      'showLegend': true,
      'subPlots': false,
      'size': 0.6,
      'titlePosition': [
        0,
        1,
      ],
      'legendPosition': [
        1,
        1,
      ],
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
      'showAxisTitles': {
        'x': false,
        'y': true,
      },
      'axisTitles': {
        'x': '',
        'y': '',
      },
    },
    'dataSource': {
      'type': 'Saved query',
      'id': '187',
    },
  },
  'dev-text': {
    'title': 'Text Widget',
    'subtitle': '',
    'subtitleLinkLabel': '',
    'subtitleHyperlink': '',
    'showTitleBar': false,
    'type': 'text',
    'filters': [],
    'groupFilter': [],
    'valueKeys': [
      {
        'text': 'Widget Section Title Example',
      },
    ],
    'chart2ValueKeys': [],
    'mapValueKeys': [],
    'formatDataFunctions': false,
    'columnNameAliases': {},
    'formattedColumnNames': {},
    'group': false,
    'groupKey': null,
    'mapGroupKey': null,
    'useMVTOption': true,
    'indexKey': null,
    'uniqueOptions': {},
    'genericOptions': {
      'showWidgetTitle': true,
      'groupByValue': false,
      'showLegend': true,
      'showTooltip': true,
      'showAxisTitles': {
        'x': true,
        'y': true,
        'y2': true,
      },
      'axisTitles': {
        'x': '',
        'y': '',
        'y2': '',
      },
      'showSubPlotTitles': true,
      'showLabels': false,
      'showCurrency': false,
      'showVertical': false,
      'mapHideSourceLayer': false,
      'mapHideTargetLayer': false,
      'mapHideArcLayer': false,
      'showLocationPins': false,
      'mapPinTooltipKey': '',
      'subPlots': false,
      'size': 0.8,
      'titlePosition': [
        0,
        0,
      ],
      'legendPosition': [
        1,
        0,
      ],
      'labelPosition': 'Bottom',
      'legendSize': 'Small',
      'baseColor': {
        'color1': '#366fe4',
        'color2': '#faaf15',
      },
      'xAxisLabelLength': 5,
      'chart1ZPosition': 'Back',
    },
    'noDataSource': true,
    'dataSource': {
      'type': null,
      'id': null,
    },
    'percentageMode': false,
    'addUserControls': false,
    'userControlHeadline': 'Benchmark By',
    'userControlKeyValues': [],
    'addTopCategories': false,
    'categoryFilter': null,
    'presetColors': [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
    'mapTooltipLabelTitles': null,
    'customColors': {},
  },
}
